sudo: false
language: bash

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

cache:
  directories:
    - ngrok

env:
  global:
    - CI="true"

script:
  - ./test.sh
  - shellcheck dehydrated letsencrypt.sh

matrix:
  fast_finish: true
